apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: api-server
  name: api-server
  namespace: test11
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: api-server
      name: api-server
    spec:
      containers:
      - args:
        - /bin/bash
        image: chiphwang/api_server
        imagePullPolicy: Always
        name: api-server
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
